# app_modules/5_visualize.py
import streamlit as st
import pandas as pd
from src.visualization.visualize import full_report, distribution_plot
import os
import json
import zipfile
import io
from pathlib import Path

def app():
    st.subheader("📈 Generated Reports and Download Center")
    st.markdown("---")
    df = st.session_state.get("df")
    
    runs_safe = st.session_state.get("train_runs") or [] 

    if df is None:
        st.warning("Upload dataset first on the **⬆️ Upload Data** page.")
        return

    st.info(f"Target column set to: **{st.session_state.get('target_col', 'not set')}**")
    st.info(f"Using **{len(runs_safe)}** training run(s) for comparison reports.")

    st.subheader("Full Automated Report")
    
    if len(runs_safe) == 0:
        st.warning("Training runs are required for the full report. Please run the pipeline on the **Run Process** page first.")
        
    if st.button("🖼️ Generate Full Report", type="primary"):
        target_col = st.session_state.get("target_col", df.columns[0])
        
        num_cols = [c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])]
        if not num_cols:
             st.error("Cannot generate report: No numeric columns found in the dataset.")
             return
             
        with st.spinner(f"⏳ Generating full report using target column: **{target_col}**..."):
            report = full_report(df, target_col=target_col, train_runs=runs_safe) 
            
        st.success("✅ Report generated and saved to disk.")
        
        # --- Create ZIP for Download ---
        output_files = []
        for key, value in report.items():
            if isinstance(value, str) and value:
                output_files.append(Path(value))
            elif isinstance(value, list):
                output_files.extend([Path(p) for p in value if p])

        if output_files:
            zip_buffer = io.BytesIO()
            with zipfile.ZipFile(zip_buffer, "a", zipfile.ZIP_DEFLATED, False) as zip_file:
                for file_path in output_files:
                    try:
                        zip_file.write(file_path, arcname=file_path.name)
                    except FileNotFoundError:
                        st.warning(f"Could not find generated file: {file_path.name} to add to zip.")

            st.download_button(
                label="⬇️ Download Full Report (ZIP)",
                data=zip_buffer.getvalue(),
                file_name="MLOps_Full_Report.zip",
                mime="application/zip",
                help="Download all generated plots and charts as a ZIP archive."
            )
        else:
            st.warning("No files were generated by `full_report` to zip.")
        
        st.markdown("---")
        st.subheader("Report Contents")
        
        for k, v in report.items():
            if isinstance(v, list):
                st.markdown(f"#### {k.replace('_', ' ').title()}")
                for p in v:
                    if p:
                        st.image(p, width='stretch') # DEPRECATION FIX
                        st.caption(f"`{p}`")
            elif isinstance(v, str) and v:
                st.markdown(f"#### {k.replace('_', ' ').title()}")
                st.image(v, width='stretch') # DEPRECATION FIX
                st.caption(f"`{v}`")
            else:
                st.info(f"{k.replace('_', ' ').title()}: None")

    st.markdown("---")
    st.subheader("Quick Single Distribution Plot")
    num_cols = [c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])]
    if num_cols:
        col = st.selectbox("Choose numeric column", num_cols, key="viz_dist_col")
        if st.button("Generate Distribution Plot (Single Feature)"):
            with st.spinner(f"Generating distribution for **{col}**..."):
                p = distribution_plot(df, col)
            st.image(p, width='stretch') # DEPRECATION FIX
            st.caption(f"`{p}`")
    else:
        st.info("No numeric columns to visualize.")